# Generated by Django 4.2.4 on 2023-09-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscoCodeClient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='alt_prefix',
            field=models.CharField(default='$', max_length=255, null=True, verbose_name='Prefix For Code Execution Commands'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='runtime_endpoint',
            field=models.CharField(default='https://emkc.org/api/v2/piston/runtimes', max_length=255, null=True, verbose_name='Query runtime endpoint'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='prefix_keyword',
            field=models.CharField(default='!dc', max_length=255, null=True, verbose_name='Chat-Prefix For Commands'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(blank=True, max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('aliases', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'version'], name='DiscoCodeCl_languag_83f49e_idx')],
            },
        ),
    ]
